### ISSUE TITLE
_examples/gettingstarted compile error

### ISSUE THREAD

**Issue by Meppo** [luno/workflow#36]
gettingstarted.go  compile error:

```
 undefined: workflow.Run (compile)go-staticcheck
```

```golang
func Workflow(d Deps) *workflow.Workflow[GettingStarted, Status] {
	b := workflow.NewBuilder[GettingStarted, Status]("getting started")

	b.AddStep(StatusStarted, func(ctx context.Context, r *workflow.Run[GettingStarted, Status]) (Status, error) {
		r.Object.ReadTheDocs = "✅"
		return StatusReadTheDocs, nil
	}, StatusReadTheDocs)
```

correct it by change 'workflow.Run'  to 'workflow.Record'

**Comment by andrewwormald** [comment]
Hi @Meppo , I see the issue is that the _example repo was given the wrong version of workflow. Will push a fix. Thanks for raising!

**Comment by andrewwormald** [comment]
@Meppo please pull the latest and it all should be working now 😄 If you pull `github.com/luno/workflow` then it would have worked due to the `replace` in the go.mod. Apologies for the inconvenience. Hope you enjoy using `Workflow`!
